import test from 'node:test';
import assert from 'node:assert/strict';
import { Store } from '../server/store.mjs';
import { Engine } from '../server/engine.mjs';
import { digest, executeProvider } from '../server/provider.mjs';
function fixture(){let now=Date.parse('2026-10-04T12:00:00Z');const store=new Store();store.createSession('buyer','csrf',{balanceMicros:10_000_000,providerEarnedMicros:0});store.createSession('other','othercsrf',{balanceMicros:10_000_000,providerEarnedMicros:0});const engine=new Engine(store,{mode:'demo'},null,()=>now);return {engine,store,setTime:t=>now=t};}
async function reserve(f,quantity=3,session='buyer'){const q=f.engine.quote(session,{start:f.engine.slots()[0].start,quantity,query:'Solana USDC payments'});const r=await f.engine.reserve(session,{quoteId:q.id});return {q,r};}
async function execute(f,scenario='success'){const {r}=await reserve(f);await f.engine.fund('buyer',r.id);f.engine.openWindow('buyer',r.id);await f.engine.execute('buyer',r.id,{scenario});return f.engine.verify('buyer',r.id);}
test('quote does not lock; reserve atomically deducts capacity; repeated reserve returns same order',async()=>{const f=fixture();const {q,r}=await reserve(f);assert.equal(f.engine.availability(q.terms.start,q.terms.end),29);const retry=await f.engine.reserve('buyer',{quoteId:q.id});assert.equal(retry.id,r.id);assert.equal(f.store.allReservations().length,1);f.store.close();});
test('competing buyers cannot oversell a window after receiving non-locking quotes',async()=>{const f=fixture(),start=f.engine.slots()[0].start;const a=f.engine.quote('buyer',{start,quantity:20,query:'Solana'}),b=f.engine.quote('other',{start,quantity:20,query:'Solana'});await f.engine.reserve('buyer',{quoteId:a.id});await assert.rejects(f.engine.reserve('other',{quoteId:b.id}),/Capacity was reserved/);assert.equal(f.engine.availability(start,start+600000),12);f.store.close();});
test('expired quote cannot reserve and cross-session access is denied',async()=>{const f=fixture();const {q,r}=await reserve(f);assert.throws(()=>f.engine.get('other',r.id),/not found/);const q2=f.engine.quote('buyer',{start:f.engine.slots()[0].start,quantity:2,query:'Solana'});f.setTime(q2.expiresAt+1);await assert.rejects(f.engine.reserve('buyer',{quoteId:q2.id}),/expired/);f.store.close();});
test('success conserves funds and duplicate fund/execute/finish do not spend twice',async()=>{const f=fixture();const r=await execute(f);assert.equal(r.status,'verified');await f.engine.fund('buyer',r.id);await f.engine.execute('buyer',r.id);const done=await f.engine.finish('buyer',r.id);assert.equal(done.status,'settled');await f.engine.finish('buyer',r.id);const data=f.engine.sessionData('buyer');assert.equal(data.balanceMicros,9_850_000);assert.equal(data.providerEarnedMicros,150_000);assert.equal(data.balanceMicros+data.providerEarnedMicros,10_000_000);assert.equal(done.settlement.refundMicros,0);f.store.close();});
for(const scenario of ['failure','late','invalid'])test(`${scenario} fails verification and returns the full funded amount`,async()=>{const f=fixture();const r=await execute(f,scenario);assert.equal(r.status,'failed');const done=await f.engine.finish('buyer',r.id);assert.equal(done.status,'refunded');assert.equal(done.settlement.refundMicros,150000);assert.equal(f.engine.sessionData('buyer').balanceMicros,10_000_000);assert.equal(f.engine.sessionData('buyer').providerEarnedMicros,0);f.store.close();});
test('unfunded, premature execution, unverified settlement and premature refund are rejected',async()=>{const f=fixture();const {r}=await reserve(f);await assert.rejects(f.engine.execute('buyer',r.id),/funded/);await f.engine.fund('buyer',r.id);await assert.rejects(f.engine.execute('buyer',r.id),/time window/);await assert.rejects(f.engine.finish('buyer',r.id),/window ends/);f.engine.openWindow('buyer',r.id);await f.engine.execute('buyer',r.id);await assert.rejects(f.engine.finish('buyer',r.id),/Verify/);f.store.close();});
test('no-show after end is fully refundable',async()=>{const f=fixture();const {r}=await reserve(f);await f.engine.fund('buyer',r.id);f.setTime(r.terms.end+1);const done=await f.engine.finish('buyer',r.id);assert.equal(done.status,'refunded');assert.equal(f.engine.sessionData('buyer').balanceMicros,10_000_000);f.store.close();});
test('all event hashes verify and are linked to one run',async()=>{const f=fixture();const r=await execute(f);const done=await f.engine.finish('buyer',r.id);let previous='0'.repeat(64);for(const {hash,...event}of done.events){assert.equal(event.previousHash,previous);assert.equal(digest(event),hash);previous=hash;}assert.equal(done.termsHash,digest(done.terms));f.store.close();});
test('concurrent execute is rejected and restart converts interrupted work to a refundable failure',async()=>{const f=fixture();const {r}=await reserve(f);await f.engine.fund('buyer',r.id);f.engine.openWindow('buyer',r.id);const a=f.engine.execute('buyer',r.id);await assert.rejects(f.engine.execute('buyer',r.id),/in progress/);await a;const current=f.engine.get('buyer',r.id);current.status='executing';f.engine.save(current);f.engine.recover();const checked=f.engine.verify('buyer',r.id);assert.equal(checked.status,'failed');assert.equal((await f.engine.finish('buyer',r.id)).status,'refunded');f.store.close();});
test('mutated output is detected by verification',async()=>{const f=fixture();const {r}=await reserve(f);await f.engine.fund('buyer',r.id);f.engine.openWindow('buyer',r.id);await f.engine.execute('buyer',r.id);const stored=f.engine.get('buyer',r.id);stored.execution.units[0].answer='tampered content pretending to be an answer';f.engine.save(stored);assert.equal(f.engine.verify('buyer',r.id).status,'failed');f.store.close();});
test('delivery outside the booked window fails even if output shape is valid',async()=>{const f=fixture();const {r}=await reserve(f);await f.engine.fund('buyer',r.id);f.engine.openWindow('buyer',r.id);await f.engine.execute('buyer',r.id);const stored=f.engine.get('buyer',r.id);stored.executionCompletedAt=r.terms.end+1;f.engine.save(stored);assert.equal(f.engine.verify('buyer',r.id).status,'failed');f.store.close();});
test('Devnet cannot be fast-forwarded or fault-injected, and reused deposit signatures are rejected',async()=>{const f=fixture();f.engine.cfg={mode:'devnet'};f.engine.chain={validateBuyer:x=>x,createVault:()=> 'fresh-test-vault',verifyDeposit:async(r,signature)=>({kind:'solana-devnet',signature,amountMicros:r.terms.totalMicros})};const {r}=await reserve(f);const signature='x'.repeat(88);await f.engine.fund('buyer',r.id,{signature});assert.throws(()=>f.engine.openWindow('buyer',r.id),/real time/);f.setTime(r.terms.start);await assert.rejects(f.engine.execute('buyer',r.id,{scenario:'failure'}),/only in the simulation/);const other=await reserve(f);await assert.rejects(f.engine.fund('buyer',other.r.id,{signature}),/already been used/);f.store.close();});
test('empty failed deliveries never display content/source/SLA passes',async()=>{const f=fixture();const r=await execute(f,'failure');assert.equal(r.verification.checks.find(x=>x.name==='Every unit has content and a source').pass,false);assert.equal(r.verification.checks.find(x=>x.name==='Sources match the declared corpus').pass,false);assert.equal(r.verification.checks.find(x=>x.name==='Observed response within SLA').pass,false);f.store.close();});
