import test from 'node:test';import assert from 'node:assert/strict';
import { Keypair,PublicKey,Transaction } from '@solana/web3.js';
import { getAssociatedTokenAddressSync,TOKEN_PROGRAM_ID } from '@solana/spl-token';
import { SolanaCustody,MEMO,memoFor } from '../server/solana.mjs';import { USDC } from '../server/config.mjs';import { Store } from '../server/store.mjs';
function fixture(){const buyer=Keypair.generate(),vault=Keypair.generate(),provider=Keypair.generate();const r={id:'r_12345678-1234-1234-1234-123456789abc',buyer:buyer.publicKey.toBase58(),vault:vault.publicKey.toBase58(),termsHash:'a'.repeat(64),terms:{totalMicros:150000},verification:{proofHash:'b'.repeat(64)}};const chain=Object.create(SolanaCustody.prototype);chain.mint=new PublicKey(USDC);chain.provider=provider;chain.check=async()=>({cluster:'devnet'});return{chain,r,buyer,vault};}
function parsedDeposit(r){const mint=new PublicKey(USDC),from=getAssociatedTokenAddressSync(mint,new PublicKey(r.buyer)),to=getAssociatedTokenAddressSync(mint,new PublicKey(r.vault));return{slot:55,transaction:{message:{accountKeys:[{pubkey:new PublicKey(r.buyer),signer:true},{pubkey:to,signer:false}],instructions:[{programId:TOKEN_PROGRAM_ID,parsed:{type:'transferChecked',info:{source:from.toBase58(),destination:to.toBase58(),mint:USDC,authority:r.buyer,tokenAmount:{amount:'150000',decimals:6}}}},{programId:MEMO,parsed:memoFor(r)}]}},meta:{err:null,preTokenBalances:[],postTokenBalances:[{accountIndex:1,mint:USDC,owner:r.vault,uiTokenAmount:{amount:'150000',decimals:6}}]}};}
test('deposit builder uses exact mint, amount, buyer signature and reservation terms memo',async()=>{const {chain,r}=fixture();chain.connection={getLatestBlockhash:async()=>({blockhash:Keypair.generate().publicKey.toBase58(),lastValidBlockHeight:500})};const p=await chain.depositTransaction(r);const tx=Transaction.from(Buffer.from(p.transaction,'base64'));assert.equal(tx.feePayer.toBase58(),r.buyer);assert.equal(tx.instructions.length,3);assert.equal(tx.instructions[1].programId.toBase58(),TOKEN_PROGRAM_ID.toBase58());assert.equal(tx.instructions[1].data.readBigUInt64LE(1),150000n);assert.equal(tx.instructions[1].data.at(-1),6);assert.equal(tx.instructions[2].data.toString(),memoFor(r));});
test('confirmed exact deposit is accepted',async()=>{const {chain,r}=fixture();chain.connection={getParsedTransaction:async()=>parsedDeposit(r)};const receipt=await chain.verifyDeposit(r,'test-signature');assert.equal(receipt.slot,55);assert.equal(receipt.amountMicros,150000);assert.equal(receipt.kind,'solana-devnet');});
for(const change of ['wrong-mint','wrong-amount','wrong-buyer','wrong-memo','wrong-vault-delta','failed-tx'])test(`deposit verifier rejects ${change}`,async()=>{const {chain,r}=fixture();const tx=parsedDeposit(r);if(change==='wrong-mint')tx.transaction.message.instructions[0].parsed.info.mint=Keypair.generate().publicKey.toBase58();if(change==='wrong-amount')tx.transaction.message.instructions[0].parsed.info.tokenAmount.amount='149999';if(change==='wrong-buyer')tx.transaction.message.accountKeys[0].signer=false;if(change==='wrong-memo')tx.transaction.message.instructions[1].parsed='other-reservation';if(change==='wrong-vault-delta')tx.meta.postTokenBalances[0].uiTokenAmount.amount='300000';if(change==='failed-tx')tx.meta.err={InstructionError:[0,'Custom']};chain.connection={getParsedTransaction:async()=>tx};await assert.rejects(chain.verifyDeposit(r,'fake'));});
test('confirmed payout retry returns the existing receipt and never sends another transfer',async()=>{const {chain,r}=fixture(),store=new Store();store.put('outbox',`payout:${r.id}`,{signature:'persisted-signature',raw:'signed',lastValidBlockHeight:500,recipient:chain.provider.publicKey.toBase58(),passed:true});let sends=0;chain.connection={getSignatureStatuses:async()=>({value:[{err:null,confirmationStatus:'confirmed'}]}),sendRawTransaction:async()=>{sends++;}};const receipt=await chain.payout(r,true,store);assert.equal(receipt.signature,'persisted-signature');assert.equal(sends,0);store.close();});
test('expired unknown payout is frozen rather than replaced',async()=>{const {chain,r}=fixture(),store=new Store();store.put('outbox',`payout:${r.id}`,{signature:'persisted',raw:'signed',lastValidBlockHeight:500,recipient:r.buyer,passed:false});let sends=0;chain.connection={getSignatureStatuses:async()=>({value:[null]}),getBlockHeight:async()=>501,sendRawTransaction:async()=>{sends++;}};await assert.rejects(chain.payout(r,false,store),/expired with unknown outcome/);assert.equal(sends,0);store.close();});
test('unconfirmed and failed payouts never get labeled settled',async()=>{for(const status of [{err:{InstructionError:1},confirmationStatus:'confirmed'},{err:null,confirmationStatus:'processed'}]){const {chain,r}=fixture(),store=new Store();store.put('outbox',`payout:${r.id}`,{signature:'persisted',raw:'signed',lastValidBlockHeight:500,recipient:r.buyer,passed:false});chain.connection={getSignatureStatuses:async()=>({value:[status]})};await assert.rejects(chain.payout(r,false,store));store.close();}});
