import { Transaction, Connection } from '@solana/web3.js';
import { Buffer } from 'buffer';
let state,quote=null,selectedStart=null,wallet=null,busy=false,query='Solana USDC payments',quantity=3;
const app=document.getElementById('app');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=x=>(x/1e6).toFixed(2);
const time=x=>new Date(x).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',hour12:false});
const fullTime=x=>new Date(x).toLocaleString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false});
const badge=(text,type='')=>`<span class="badge ${type}">${esc(text)}</span>`;
const btn=(text,action,secondary=false,extra='')=>`<button class="btn ${secondary?'secondary':''}" data-action="${action}" ${busy?'disabled':''} ${extra}>${text}</button>`;
function notice(text,error=false){const n=document.getElementById('notice');n.className=`visible ${error?'error':''}`;n.textContent=text;setTimeout(()=>{n.className='';n.textContent='';},7000);}
async function api(path,body){const res=await fetch(`/api/${path}`,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-CSRF-Token':state.csrf}:{},body:body?JSON.stringify(body):undefined});const data=await res.json();if(!res.ok)throw Error(data.error||'Request failed');return data;}
async function refresh(){state=await api('state');if(!state.slots.some(s=>s.start===selectedStart))selectedStart=state.slots[0]?.start;}
function route(){return location.hash.slice(1)||'home';}
const stageStatus={reserved:'Awaiting escrow',escrowed:'Capacity funded',executing:'Provider executing',executed:'Ready to verify',verified:'SLA passed',failed:'Refund due',settling:'Settlement confirming',refunding:'Refund confirming',settled:'Settled',refunded:'Refunded'};
function header(){return `<header class="nav"><a class="brand" href="#home"><img src="/assets/logo.svg" alt="">COMMIT</a><nav class="links" aria-label="Main navigation">${[['home','How it works'],['reserve','Reserve capacity'],['commitments','My commitments'],['supply','Provider desk'],['developers','Developers']].map(([id,title])=>`<a href="#${id}" ${route()===id?'class="active" aria-current="page"':''}>${title}</a>`).join('')}</nav><span class="edition">World’s Fair edition</span></header>`;}
function footer(){return `<footer class="foot"><span>COMMIT / Agent Capacity Reservation Layer<br>Independent competition prototype · ${state.mode==='demo'?'Simulation, no blockchain funds':'Solana Devnet, test tokens only'}</span><span>Provider & verifier operated by Commit. Devnet custody is project-operated.<br><a href="#developers">Read the trust assumptions and integration details ↗</a></span></footer>`;}
function modebar(){return `<div class="modebar">${badge(state.mode==='demo'?'Interactive simulation · no real funds':'Solana Devnet · Circle test USDC')}<span class="wallet-note">${state.mode==='demo'?`Demo wallet $${money(state.balance.balanceMicros)}`:wallet?`Buyer ${esc(wallet.publicKey.toBase58().slice(0,6))}…${btn('Connected','connect',true)}`:btn('Connect Devnet wallet','connect',true)}</span></div>`;}
function home(){return `<section class="hero"><div><div class="eyebrow">Forward market for agent capacity</div><h1>Tomorrow’s capacity.<br>Committed today.</h1><p>Your agent has a deadline. Reserve a future service window, lock the price, and define what delivery means before the work begins.</p><div class="actions"><a class="btn" href="#reserve">Reserve a window <span>↗</span></a><a class="btn secondary" href="#developers">See how it works</a></div><div class="micro">Quote → Reserve → Escrow → Execute → Verify → Settle / Refund<br>${state.mode==='demo'?'Replay the complete flow in simulation. Devnet integration is available separately.':'Test with official Circle USDC on Solana Devnet. Project-operated custody.'}</div></div><div class="hero-art"><img src="/assets/reserved-capacity.png" alt="An open archive box with a reserved slot for a future commitment"><div class="artifact-label"><span>01 / A place for work that hasn’t happened yet.</span><span>RESERVED</span></div></div></section><section class="factbar"><div><b>A fixed future window</b><span>Time and quantity are part of the commitment.</span></div><div><b>A price agreed in advance</b><span>One quote. Clear delivery and refund terms.</span></div><div><b>A result you can check</b><span>Output, SLA checks and the money trail together.</span></div></section><section><div class="section-title"><h2>Buy certainty for<br>the work ahead.</h2><p>Spot payments handle a call right now. Commit adds an agreement for the capacity your workflow will need later.</p></div><div class="how"><div><span class="number">01</span><h3>Reserve the work window.</h3><p>Choose a future time and quantity. A quote shows the terms; confirmation locks the participating provider’s declared quota.</p></div><div><span class="number">02</span><h3>Fund, execute, verify.</h3><p>Fund the order. During its window, run the retrieval provider and check its output against the agreed delivery criteria.</p></div><div><span class="number">03</span><h3>Pay for verified delivery.</h3><p>Success releases payment to the provider. A missed SLA produces a full refund. Both outcomes remain on one record.</p></div></div></section>`;}
function slotTable(){return `<table class="window-table"><thead><tr><th>Future window · local time</th><th>Available</th><th>Price / unit</th></tr></thead><tbody>${state.slots.map(s=>`<tr class="${selectedStart===s.start?'selected':''}"><td><button class="slot" data-slot="${s.start}" aria-pressed="${selectedStart===s.start}"><span class="radio"></span><span>${time(s.start)} – ${time(s.end)}<br><span class="micro">${fullTime(s.start).split(',')[0]} · 10-minute window</span></span></button></td><td>${s.available} / ${s.capacity}<span class="bar"><i style="width:${Math.round(s.available/s.capacity*100)}%"></i></span></td><td>$0.05</td></tr>`).join('')}</tbody></table>`;}
function terms(terms){return `<dl><div><dt>Reserved service</dt><dd>ResearchNode · Search v1</dd></div><div><dt>Future window</dt><dd>${fullTime(terms.start)} – ${time(terms.end)}</dd></div><div><dt>Quantity</dt><dd>${terms.quantity} retrieval units</dd></div><div><dt>Delivery SLA</dt><dd>≤ ${terms.latencyLimitMs/1000}s response<br>Source + content for every unit</dd></div><div><dt>Failure policy</dt><dd>Full refund if SLA fails</dd></div><div><dt>Settlement asset</dt><dd>${esc(terms.currency)}</dd></div></dl>`;}
function reserveView(){return `<section class="workspace">${modebar()}<div class="section-title"><div><div class="eyebrow">Capacity desk / 01</div><h2>Reserve the next window.</h2></div><p>Book a project-operated retrieval provider.<br>A quote is an offer; only a reservation locks quota.</p></div><div class="grid"><div class="panel"><h3>Available future capacity</h3>${slotTable()}<div class="formrow"><label><span class="label">Query</span><input id="query" value="${esc(query)}" maxlength="240" placeholder="Solana USDC payments"></label><label><span class="label">Retrieval units</span><input id="quantity" type="number" min="1" max="20" value="${quantity}"></label></div><p class="terms-note">Each unit performs a retrieval over a fixed, public-source corpus. The result is computed for your query. This demo does not call a live LLM.</p><div class="actions">${btn('Get a fixed-price quote →','quote')}${btn('Refresh availability','refresh',true)}</div></div><div class="panel summary">${quote?`<div class="eyebrow">Your quote / capacity not locked</div>${terms(quote.terms)}<div class="price"><strong>$${money(quote.terms.totalMicros)}</strong><span>TOTAL · ${quote.terms.quantity} × $0.05</span></div><p class="terms-note">Quote expires ${time(quote.expiresAt)}. Confirmation reserves quota and accepts the displayed terms. Escrow is a separate step.</p>${btn('Confirm capacity reservation →','reserve')}<p class="terms-note">Project-operated provider & verifier. No external customer validation is claimed.</p>`:`<div class="quote-empty"><span class="number">A future window.<br>A clear promise.</span><p>Your price, SLA and refund terms will appear here before you confirm a reservation.</p><p class="terms-note">Capacity is declared by the participating provider. This prototype does not reserve GPUs or upstream API accounts.</p></div>`}</div></div></section>`;}
function commitments(){return `<section class="workspace">${modebar()}<div class="section-title"><div><div class="eyebrow">Your capacity desk</div><h2>Promises, with a record.</h2></div><a href="#reserve" class="btn">New reservation ↗</a></div><p>Every reservation keeps its terms, delivered output, verification and settlement on one record.</p><div class="reservation-list">${state.reservations.length?state.reservations.map(r=>`<button class="reservation-item" data-record="${r.id}"><div><b>${r.terms.quantity} retrieval units · $${money(r.terms.totalMicros)}</b><span>${fullTime(r.terms.start)} – ${time(r.terms.end)} · ${esc(r.terms.query)}</span></div><div>${badge(stageStatus[r.status],r.status==='settled'?'green':r.status==='refunded'?'red':'')}<br><span>${esc(r.id.slice(0,12))}… →</span></div></button>`).join(''):`<div class="empty"><h3>Your first future commitment starts here.</h3><p>Reserve capacity, then watch the work and its payment reach a clear outcome.</p><a href="#reserve" class="btn">Reserve capacity →</a></div>`}</div></section>`;}
function actionPanel(r){let title,desc,controls;
  switch(r.status){
    case'reserved':title='Fund this reservation.';desc=state.mode==='demo'?'Move the quoted amount from the demo wallet into simulated escrow.':'Sign a transaction for the exact quoted Circle Devnet USDC amount. It goes to a unique, project-operated vault for this reservation.';controls=btn(state.mode==='demo'?'Fund simulated escrow →':'Deposit Devnet USDC →','fund');break;
    case'escrowed': {const now=Math.max(Date.now(),r.demoClock||0);if(now>=r.terms.end){title='The delivery window has ended.';desc='No work was executed. Return the full escrow to the buyer.';controls=btn('Refund unused reservation →','finish');}else if(now<r.terms.start){title='Your future capacity is booked.';desc=state.mode==='demo'?'The provider is reserved for a future window. For this simulation, advance only the demo clock to that window.':'Real-time booking is active. Execution opens at the booked time; refresh when the window starts.';controls=state.mode==='demo'?btn('Start booked window (demo clock) →','open-window'):btn('Refresh window status','refresh',true);}else{title='Execute inside the reserved window.';desc='The provider retrieves cited material from its declared corpus. Verify separately before releasing payment.';controls=(state.mode==='demo'?`<label><span class="label">Demo delivery scenario</span><select id="scenario"><option value="success">Successful delivery</option><option value="failure">Provider unavailable → refund</option><option value="late">Missed response deadline → refund</option><option value="invalid">Missing citation → refund</option></select></label>`:'')+btn('Execute reserved task →','execute');}break;}
    case'executed':title='Compare delivery with the agreed SLA.';desc='Check quantity, observed latency, citation presence and integrity. These checks do not establish semantic truth.';controls=btn('Verify delivery →','verify');break;
    case'verified':title='Delivery passed. Settle the commitment.';desc='Release the escrow to the provider and preserve the receipt.';controls=btn('Settle verified delivery →','finish');break;
    case'failed':title='Delivery missed the SLA. Refund the buyer.';desc='The provider receives nothing for this failed order. Return the full escrow.';controls=btn('Refund the buyer →','finish');break;
    case'settling':case'refunding':title='Payment reconciliation in progress.';desc='Retry checks the same persisted transaction signature. It does not create a second payment.';controls=btn('Check payment outcome →','finish');break;
    case'settled':title='Committed. Delivered. Settled.';desc='The provider received the verified order’s payment. The complete record is ready to review.';controls=`<a href="#reserve" class="btn secondary">Reserve another window ↗</a>`;break;
    case'refunded':title='A missed promise, a clear refund.';desc='The buyer received the full order amount back. The failure and refund stay on the same record.';controls=`<a href="#reserve" class="btn secondary">Try a successful delivery ↗</a>`;break;
    default:title='Provider execution in progress.';desc='Refresh after the action completes.';controls=btn('Refresh','refresh',true);
  }return `<section class="next-action"><h3>${title}</h3><p>${desc}</p><div class="actions">${controls}</div></section>`;
}
function recordView(id){const r=state.reservations.find(r=>r.id===id);if(!r)return `<section class="workspace"><h2>Reservation unavailable.</h2><p>This reservation belongs to another session or was not found.</p><a href="#commitments">Back to your commitments</a></section>`;
  const completed=[true,true,!!r.payment,!!r.execution,!!r.verification,!!r.settlement,!!r.settlement];
  const flow=['Quote','Reserve','Escrow','Execute','Verify',r.verification&&!r.verification.passed?'Refund':'Settle','Receipt'];
  const output=r.execution?`<div class="results"><h3>Delivered output</h3><p class="terms-note">Computed retrieval from a fixed corpus · ${r.execution.observedLatencyMs} ms observed response · project-operated</p>${r.execution.error?`<p class="error-block">${esc(r.execution.error)}</p>`:r.execution.units.slice(0,3).map(u=>`<article class="result"><span class="label">Retrieval unit ${u.unit} / ${r.terms.quantity}</span><p>${esc(u.answer||'No answer delivered.')}</p><div class="sources">${u.citations.map(c=>`<a href="${esc(c.url)}" target="_blank" rel="noreferrer">${esc(c.title)} ↗</a>`).join('')}</div></article>`).join('')}${r.execution.units.length>3?'<p class="terms-note">Remaining units are included in the full evidence JSON.</p>':''}</div>`:'';
  const verification=r.verification?`<div class="results"><h3>Delivery verification</h3><ul class="checks">${r.verification.checks.map(c=>`<li><span>${esc(c.name)}</span><strong class="${c.pass?'check-pass':'check-fail'}">${c.pass?'PASS':'FAIL'}</strong></li>`).join('')}</ul><p class="terms-note">${esc(r.verification.limitation)}</p></div>`:'';
  const receipt=r.settlement?`<div class="receipt"><h3>Final money trail</h3><div class="amounts"><div><b>$${money(r.settlement.providerMicros)}</b><span>PROVIDER PAID</span></div><div><b>$${money(r.settlement.refundMicros)}</b><span>BUYER REFUNDED</span></div><div><b>$0.00</b><span>ESCROW LEFT</span></div></div><p class="terms-note">${r.settlement.kind==='simulation'?'Simulation ledger only. No blockchain transaction.':`Confirmed Devnet USDC transfer. <a href="${esc(r.settlement.explorer)}" target="_blank" rel="noreferrer">View transaction ↗</a>`}</p></div>`:'';
  return `<section class="workspace">${modebar()}<div class="record-head"><div><div class="eyebrow">Commitment record</div><h2>One window. One promise.</h2><div class="small">${esc(r.id)} · ${state.mode==='demo'?'simulation':'devnet'}</div></div>${badge(stageStatus[r.status],r.status==='settled'?'green':r.status==='refunded'?'red':'')}</div><div class="flow">${flow.map((name,i)=>`<div class="flow-step ${completed[i]?'done':''} ${name==='Refund'?'fail':''}"><i>${completed[i]?'✓':i+1}</i>${name}</div>`).join('')}</div>${actionPanel(r)}<div class="grid"><div class="panel summary"><h3>The agreement</h3>${terms(r.terms)}<dl><div><dt>Task</dt><dd>${esc(r.terms.query)}</dd></div></dl>${output}${verification}${receipt}</div><aside class="panel"><h3>Evidence, from start to finish</h3><ol class="timeline">${r.events.map(e=>`<li><b>${esc(e.type.replaceAll('_',' '))}</b><span>${esc(new Date(e.at).toISOString())}<br>${esc(e.hash.slice(0,22))}…</span></li>`).join('')}</ol><p class="terms-note">Hash-linked local events. ${state.mode==='demo'?'Demo-clock events are explicitly marked. No chain confirmation is implied.':'Deposit and payout memos bind this reservation and terms to the chain.'}</p>${r.payment?.explorer?`<p class="terms-note"><a href="${esc(r.payment.explorer)}" target="_blank" rel="noreferrer">Confirmed escrow deposit ↗</a></p>`:''}<div class="code">TERMS SHA256<br>${esc(r.termsHash)}${r.vault?`<br><br>DEVNET VAULT<br>${esc(r.vault)}`:''}</div><div class="actions results">${btn('Download evidence JSON ↗','evidence',true)}</div><p class="terms-note">One record per run. Prior Commit evidence is not mixed into this edition.</p></aside></div></section>`;
}
function supply(){const settled=state.reservations.filter(r=>r.status==='settled'),refunded=state.reservations.filter(r=>r.status==='refunded');return `<section class="workspace">${modebar()}<div class="eyebrow">Provider desk / declared capacity</div><h2>Make a promise<br>you can measure.</h2><p>This read-only prototype desk shows the project-operated ResearchNode supply and outcomes in your session.</p><div class="factbar"><div><b>${settled.length} settled orders</b><span>Verified retrieval orders in this session.</span></div><div><b>${refunded.length} refunded orders</b><span>Refunds remain visible for review.</span></div><div><b>32 units / window</b><span>Declared retrieval quota, not GPU reservations.</span></div></div><div class="grid"><div class="panel"><h3>Published future windows</h3>${slotTable()}<p class="terms-note">Database transactions prevent selling the same declared quota twice within this standalone app. Provider capacity is fixed in this version; external onboarding is a next step.</p></div><div class="panel"><span class="capacity-count">$${money(state.reservations.reduce((n,r)=>n+(r.settlement?.providerMicros||0),0))}</span><h3>Verified provider payout</h3><p>Session-level sample, not revenue or traction. Use real pilot feedback before changing capacity or pricing.</p><p class="terms-note">Primary provider and verifier share an operator. No independent reliability rating is claimed.</p></div></div></section>`;}
function developers(){return `<section class="workspace">${modebar()}<div class="eyebrow">Developers / trust and architecture</div><h2>A reservation layer<br>for agent workflows.</h2><div class="developer-grid"><div><h3>The running prototype</h3><p>HTTP API → atomic SQLite capacity ledger → project-operated retrieval provider → deterministic delivery verifier → simulated ledger or Solana SPL-token transfer.</p><div class="code">POST /api/quote<br>POST /api/reserve<br>POST /api/reservations/:id/fund<br>POST /api/reservations/:id/execute<br>POST /api/reservations/:id/verify<br>POST /api/reservations/:id/finish<br>GET  /api/reservations/:id/evidence</div><h3>Agent-facing primitives</h3><p>The quote pins time, quantity, price and SLA. A reservation consumes declared capacity atomically. Funded orders execute only inside their window. Payment waits for verification.</p><h3>Isolation by construction</h3><p>Separate repository, port 4317, namespaced configuration and private state directory. No existing Commit key, contract, API, database, branch or domain is used.</p></div><div><h3>Solana + USDC</h3><p>Devnet uses Circle’s official test USDC mint and TransferChecked. A unique wallet holds each reservation’s tokens; transaction memos bind the reservation, terms hash and verification hash.</p><h3>Explicit trust assumptions</h3><ul><li>This is project-operated custody, not a custom escrow program. The operator controls vault keys and verification.</li><li>Declared quotas do not reserve upstream hardware or API resources.</li><li>Verification checks schema, sources and latency. It does not independently prove that an answer is correct.</li><li>All demo scenarios and balances are simulations. Devnet requires fresh test wallets and faucet funding.</li></ul><h3>What comes next</h3><p>External provider pilots, provider-signed capacity offers, PDA custody and an independently reviewable verifier model. These are roadmap items, not shipped features.</p><div class="code">Asset: ${esc(state.mode==='demo'?'simulated USD':'Circle USDC / Solana Devnet')}<br>No mainnet route. No existing deployment target.</div></div></div></section>`;}
function render(){if(!state)return;const view=route();let content=view==='home'?home():view==='reserve'?reserveView():view==='commitments'?commitments():view==='supply'?supply():view.startsWith('record/')?recordView(view.slice(7)):developers();app.innerHTML=`<div class="shell">${header()}<main>${content}</main>${footer()}</div>`;bind();}
async function connect(){const provider=window.phantom?.solana||window.solana||window.solflare;if(!provider?.connect||!provider?.signTransaction)throw Error('Install a Solana wallet with transaction signing, and use a separate Devnet account.');await provider.connect();wallet=provider;render();notice('Wallet connected. Transactions will use Solana Devnet only.');}
async function doAction(action){
  if(busy)return;const id=route().startsWith('record/')?route().slice(7):null;
  const scenario=document.getElementById('scenario')?.value||'success';
  query=document.getElementById('query')?.value||query;quantity=Number(document.getElementById('quantity')?.value||quantity);
  busy=true;document.querySelectorAll('button').forEach(x=>x.disabled=true);
  try{
    if(action==='connect'){await connect();return;}
    if(action==='refresh'){await refresh();notice('Capacity and status refreshed.');}
    else if(action==='quote'){quote=await api('quote',{start:selectedStart,quantity,query});notice('Quote ready. Capacity is not yet locked.');}
    else if(action==='reserve') {if(state.mode==='devnet'&&!wallet)await connect();const r=await api('reserve',{quoteId:quote.id,buyer:wallet?.publicKey.toBase58()});quote=null;await refresh();location.hash=`record/${r.id}`;notice('Capacity reserved. Fund escrow to prepare execution.');}
    else if(action==='fund'&&state.mode==='devnet') {
      if(!wallet)await connect();const r=state.reservations.find(r=>r.id===id);if(wallet.publicKey.toBase58()!==r.buyer)throw Error('Reconnect the buyer wallet used for this reservation.');
      let signature=sessionStorage.getItem(`commit-wf-deposit:${id}`);
      if(!signature){const p=await api(`reservations/${id}/deposit-transaction`,{});const tx=Transaction.from(Buffer.from(p.transaction,'base64'));const signed=await wallet.signTransaction(tx);const rpc=new Connection(state.rpc,'confirmed');signature=await rpc.sendRawTransaction(signed.serialize());sessionStorage.setItem(`commit-wf-deposit:${id}`,signature);const result=await rpc.confirmTransaction({signature,blockhash:p.blockhash,lastValidBlockHeight:p.lastValidBlockHeight},'confirmed');if(result.value.err)throw Error('Deposit failed. Check its signature before trying again.');}
      await api(`reservations/${id}/fund`,{signature});await refresh();notice('Devnet USDC deposit verified.');
    }else if(action==='evidence'){const evidence=await api(`reservations/${id}/evidence`);const blob=new Blob([JSON.stringify(evidence,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`commit-worldsfair-${id}.json`;a.click();URL.revokeObjectURL(url);notice('Evidence downloaded.');}
    else{await api(`reservations/${id}/${action}`,action==='execute'?{scenario}:{});await refresh();notice(action==='finish'?'Payment outcome recorded.':action==='verify'?'Delivery checked against the agreed terms.':'Commitment updated.');}
  }catch(e){notice(e.message,true);}finally{busy=false;render();}
}
function bind(){document.querySelectorAll('[data-action]').forEach(el=>el.addEventListener('click',()=>doAction(el.dataset.action)));document.querySelectorAll('[data-slot]').forEach(el=>el.addEventListener('click',()=>{query=document.getElementById('query')?.value||query;quantity=Number(document.getElementById('quantity')?.value||quantity);selectedStart=Number(el.dataset.slot);quote=null;render();}));document.querySelectorAll('[data-record]').forEach(el=>el.addEventListener('click',()=>{location.hash=`record/${el.dataset.record}`;}));}
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
refresh().then(render).catch(e=>{app.innerHTML=`<div class="loading">COMMIT<br><span>${esc(e.message)}</span></div>`;});
